version: '3'
networks:
  esnet:
services:
  # 主节点
  es_master:
    container_name: es_master
    hostname: es_master
    image: elasticsearch:7.1.0
    restart: always
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /usr/local/src/es_master.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /data/es/es_master/data:/usr/share/elasticsearch/data
      - /data/es/es_master/logs:/usr/share/elasticsearch/logs
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      esnet:
        aliases:
          - es_master
  # 从节点
  es_node1:
    container_name: es_node1
    image: elasticsearch:7.1.0
    restart: always
    volumes:
      - /usr/local/src/es_node1.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /data/es/es_node1/data:/usr/share/elasticsearch/data
      - /data/es/es_node1/logs:/usr/share/elasticsearch/logs
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      esnet:
        aliases:
          - es-node-1

  # kibana 监控
  kibana:
    image: kibana:7.1.0
    container_name: kibana
    volumes:
      - /usr/local/src/kibana.yml:/usr/share/kibana/config/kibana.yml
      - /data/kibana/data:/usr/share/kibana/data
      - /data/kibana/logs:/usr/share/kibana/logs
    environment:
      - i18n_locale=zh-CN
      - xpack_graph_enabled=true
      - timelion_enabled=true
      - xpack_monitoring_collection_enabled=true
    ports:
      - 5601:5601
    networks:
      - esnet
  # Cerebro
  cerebro:
    image: lmenezes/cerebro:0.8.4
    container_name: cerebro
    ports:
      - "9000:9000"
    command:
      - -Dhosts.0.host=http://es_master:9200
    networks:
      - esnet