version: '2.2'
services:
  cerebro:
    image: lmenezes/cerebro:0.8.4
    container_name: cerebro
    ports:
      - "9000:9000"
    command:
      - -Dhosts.0.host=http://elasticsearch:9200
    networks:
      - es7net
  kibana:
    image: kibana:7.6.2
    container_name: kibana
    environment:
      - xpack_graph_enabled=false
      - xpack_monitoring_collection_enabled=true
      - timelion_enabled=false
    ports:
      - 5601:5601
    networks:
      - es7net
  elasticsearch:
    image: elasticsearch:7.6.2
    container_name: es
    hostname: es_node1
    extra_hosts:
      - "es_node1:192.168.147.102"
    environment:
      - cluster.name=elastic
      - node.name=es_node1
      - node.master=true
      - node.data=true
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.seed_hosts=es_node1
      - network.publish_host=elasticsearch
      - cluster.initial_master_nodes=es_node1
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /data/es/single_es/data:/usr/share/elasticsearch/data
      - /data/es/single_es/logs:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - es7net
volumes:
  esdata:
    driver: local

networks:
  es7net:
    driver: bridge