version: '2.2'
services:
  kibana:
    image: kibana:7.6.2
    container_name: sin_kibana
    environment:
      - SERVER.PORT=5601
      - XPACK.MONITORING.UI.CONTAINER.ELASTICSEARCH.ENABLED=false
      - elasticsearch.ssl.verify=false
      - XPACK_GRAPH_ENABLED=false
      - xpack_monitoring_collection_enabled=true
      - timelion_enabled=false
    ports:
      - 5601:5601
    networks:
      - es7net
  elasticsearch:
    image: elasticsearch:7.6.2
    container_name: single_es
    hostname: single_es
    environment:
      - cluster.name=elastic
      - node.name=single_es
      - node.master=true
      - node.data=true
      - http.port=9202
      - transport.port=9302
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.seed_hosts=single_es
      - network.publish_host=elasticsearch
      - cluster.initial_master_nodes=single_es
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /data:/usr/share/elasticsearch/data
      - /data/es/single_es/logs:/usr/share/elasticsearch/logs
    ports:
      # 对外只需开放9200
      - 9202:9202
    networks:
      - es7net
  # 类似es_head的es管理工具
  cerebro:
    image: lmenezes/cerebro:0.8.4
    container_name: cerebro
    ports:
      - 9000:9000
    command:
      - -Dhosts.0.host=http://elasticsearch:9202
    networks:
      - es7net

# 服务配置
volumes:
  esdata:
    driver: local #默认值

networks:
  es7net:
    driver: bridge #默认值